# Generated by Django 4.2 on 2025-06-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_department_alter_doctor_description_and_more'),
        ('review', '0002_alter_review_options_rename_doctor_iin_review_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='Врач'),
        ),
    ]
